version: '3'
services:
  web:
    image: node:12-alpine
    environment:
      - REACT_APP_API_ENDPOINT=https://aeffmbtestapi.azurewebsites.net/
    ports:
      - "3000:3000"
      - "35729:35729"
    volumes:
      - ./client:/app
    command: sh -c "npm i && npm run start"
    working_dir: /app
